#!/bin/bash
# Build MaterialX for Android ARM64
set -euo pipefail
NDK_DIR="$1"; OUTPUT_DIR="$2"; BUILD_DIR="$3"; API_LEVEL="${4:-24}"
mkdir -p "$BUILD_DIR" && cd "$BUILD_DIR"
git clone --depth 1 --branch v1.39.0 https://github.com/AcademySoftwareFoundation/MaterialX.git src
cd src
cmake -B build \
  -DCMAKE_TOOLCHAIN_FILE="$NDK_DIR/build/cmake/android.toolchain.cmake" \
  -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM="android-$API_LEVEL" \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$OUTPUT_DIR" \
  -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DMATERIALX_BUILD_TESTS=OFF -DMATERIALX_BUILD_PYTHON=OFF -DMATERIALX_BUILD_VIEWER=OFF \
  -DMATERIALX_BUILD_GRAPHIO=OFF -DMATERIALX_BUILD_RENDER=OFF -DMATERIALX_BUILD_GEN_GLSL=OFF \
  -DMATERIALX_BUILD_GEN_MDL=OFF -DMATERIALX_BUILD_GEN_OSL=OFF -DMATERIALX_BUILD_GEN_HLSL=OFF \
  -DMATERIALX_BUILD_GEN_MSL=OFF
cmake --build build -j$(nproc)
cmake --install build

# Also build shared
cmake -B build-shared \
  -DCMAKE_TOOLCHAIN_FILE="$NDK_DIR/build/cmake/android.toolchain.cmake" \
  -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM="android-$API_LEVEL" \
  -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="$OUTPUT_DIR" \
  -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
  -DMATERIALX_BUILD_TESTS=OFF -DMATERIALX_BUILD_PYTHON=OFF -DMATERIALX_BUILD_VIEWER=OFF \
  -DMATERIALX_BUILD_GRAPHIO=OFF -DMATERIALX_BUILD_RENDER=OFF -DMATERIALX_BUILD_GEN_GLSL=OFF \
  -DMATERIALX_BUILD_GEN_MDL=OFF -DMATERIALX_BUILD_GEN_OSL=OFF -DMATERIALX_BUILD_GEN_HLSL=OFF \
  -DMATERIALX_BUILD_GEN_MSL=OFF
cmake --build build-shared -j$(nproc)
cmake --install build-shared
echo "MaterialX built"
